@lvt_example

@php
    $path = \Illuminate\Support\Facades\URL::current();
    $page = request()->get('page', 1);
    $users = new \Illuminate\Pagination\LengthAwarePaginator(array_fill(0, 50, 1), 50, 5, $page,['path' => $path]);
@endphp

<h1 class="mt-3">Default</h1>
<div class="mt-3">
    {{ $users->links('lvt::links.default') }}
</div>

<p class="mt-3">This line is generated by default paginater</p>
<div class="mt-3">
    {{ $users->links() }}
</div>

<b-badge class="mt-3" v-b-toggle.default>Source Code</b-badge>
<b-collapse id="default" class="mt-2"><code-php v-pre>@php echo e( <<<'DOC'
    {{ $users->links('lvt::links.default') }}
    {{ $users->links() }}
DOC
)@endphp</code-php><p class="mt-3">The `lvt` prefix is the namespace that VueAdmin registered</p></b-collapse>

@endlvt_example